### ISSUE TITLE
ModuleNotFoundERror

### ISSUE THREAD

**Issue by andrewm659** [peekjef72/veeam_exporter#7]
Getting this when trying to run the script.
```
veeam_exporter]$ /opt/rh/rh-python38/root/usr/bin/python3.8 ./veeam_exporter_cmd -n -v
Traceback (most recent call last):
  File "./veeam_exporter_cmd", line 5, in <module>
    from veeam_exporter.veeam_exporter import main
  File "/opt/monitoring/veeam_exporter/veeam_exporter_src/veeam_exporter/veeam_exporter.py", line 12, in <module>
    from veeam_exporter.constants import (PKG_NAME, PKG_VERSION, EXPORTER_CONFIG_NAME)
ModuleNotFoundError: No module named 'veeam_exporter.constants'; 'veeam_exporter' is not a package
```

**Comment by andrewm659** [comment]
Figured this out.
