### ISSUE TITLE
exporter just crashes

### ISSUE THREAD

**Issue by sthartmannsopra** [peekjef72/veeam_exporter#8]
Hello,

I've discovered your veeam exporter and tried to deploy one on my environment. However, it just crashes at launch, I can't really understand what is wrong in my configuration. Here are some logs 👍 

The config file /usr/lib/python3.10/site-packages/veeam_exporter/conf/config.yml has been set, and i run the exporter with this command: python3 veeam_exporter_cmd -n -v

Message: 'veeam_exporter 1.0.6 starting....'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 983, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 904, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by peekjef72** [comment]
Hi,

Sorry, that you have problem with the exporter !

the error message is not really clear for me; an exception occurred in the logging python module; it should be due to an untested part of the exporter or a misconfiguration somewhere. It seems to me that it should have to do with the "logging" feature.

Do you use syslog or a specific location to write logs ?
If you use the default config that is syslog, the prog should have access to /dev/log (unix)

from [veeam_exporter](https://github.com/peekjef72/veeam_exporter)/[veeam_exporter_src](https://github.com/peekjef72/veeam_exporter/tree/master/veeam_exporter_src)/[veeam_exporter](https://github.com/peekjef72/veeam_exporter/tree/master/veeam_exporter_src/veeam_exporter)/veeam_exporter.py on line 258:
```python
handler = logging.handlers.SysLogHandler(address = '/dev/log')
```

You may also try to increase the loglevel to have more details, but if it has to do with logging it will fail even faster ! (--log.level=debug)
You may also try to set a specific file for logging (temporary) to test if it concerns syslog.

Give me some feedbacks.
